### ISSUE TITLE
Confusion on potential.depvars

### ISSUE THREAD

**Issue by SimplySav101** [markolipka/readCNV#1]
Hello! First I would like to thank you for providing this excellent code. I'm having a lovely time working with it but have run into some errors. I am working with CNV files (which cannot be attached to github) trying to plot my CTD data. My issue lies with the potential.depvars line in the plot.ctd function. I am not quite sure what I should be comparing or how it is matching within the code. My graphs are not looking like the smooth curves in your example. I have attached the relevant code but am open to exchanging emails so that I can send you the CNV file in question.

  potential.id.vars <- c("prDM", "t090C", "c0uS/cm","sbox0Mm/Kg","scan","flECO-AFL","turbWETntu0", "nbin", "bad_flag", "interval",
                         "latitude", "longitude")
  potential.depvars <- c("prDM","t090C", "c0uS/cm","sbox0Mm/Kg","flECO-AFL","turbWETntu0")

Also, I noticed you have a variable "pr" but I have not seen that in your example data or mentioned anywhere else. Could you explain where that comes from please?
![troubleshooting](https://user-images.githubusercontent.com/75280083/111383023-14544380-867e-11eb-8bc5-02a0e555ef81.png)

**Comment by markolipka** [comment]
Hi @SimplySav101 ,

thanks for the issue!
Long time ago that I wrote and used that code the last time. Let's see if we can make it work with your data.

Your problem might be, that the wrong water depth parameter is chosen for plotting.
Until now, it was not possible to chose the water depth parameter directly via a function argument. I implemented this now, hope it works for you.

If not, you could email me your cnv data and I'd try to adapt the script to the parameter names (and maybe further specialties) of the SBE CTD system you are using.

**Comment by markolipka** [comment]
> Also, I noticed you have a variable "pr" but I have not seen that in your example data or mentioned anywhere else. Could you explain where that comes from please?

Not sure about that, but I guess this is an optional water depth parameter in the SBE CTD systems we were dealing with.

**Comment by SimplySav101** [comment]
Thank you for your reply! Ah, I thought that might be the problem but my data does not seem to have a converted depth column and since pressure is often used as a depth proxy, I thought I could get away with it! I would be happy to send you one of the files and the code I used thus far. Ideally, I want to be able to plot my data but then extract the metrics to be paired with catch data and used in a spatial analysis. I would very much like to email you. What is the best contact?

**Comment by markolipka** [comment]
marko.lipka@posteo.de

**Comment by markolipka** [comment]
recent commits made the read.cnv.file() function more agnostic about different metadata and parameters in cnv files.
